# _                                _                         
#| |layout_config.py              | |                        
#| | _____   _____  __ _ _ __   __| |_ ____      ___ __  ___ 
#| |/ _ \ \ / / _ \/ _` | '_ \ / _` | '_ \ \ /\ / / '_ \/ __|
#| | (_) \ V /  __/ (_| | | | | (_| | |_) \ V  V /| | | \__ \
#|_|\___/ \_/ \___|\__,_|_| |_|\__,_| .__/ \_/\_/ |_| |_|___/
#                                   | |                      
#                                   |_|     
import json
import os

class LayoutConfig:
    @classmethod
    def save_to_file(cls, filepath="simulator_settings.json"):
        settings = {}
        for key in dir(cls):
            if key.isupper() and not key.startswith('_'):
                value = getattr(cls, key)
                if not callable(value):
                    settings[key] = value
        
        with open(filepath, 'w') as f:
            json.dump(settings, f, indent=4)
        return filepath
    
    @classmethod
    def load_from_file(cls, filepath="simulator_settings.json"):
        if not os.path.exists(filepath):
            return False
        
        with open(filepath, 'r') as f:
            settings = json.load(f)
        
        for key, value in settings.items():
            if hasattr(cls, key):
                setattr(cls, key, value)
        
        return True
    
    BASE_FONT_FAMILY = "Arial"
    BASE_FONT_SCALE = 1.0
    ACCENT_COLOR = "#DD4443"
    FONT_SIZE_SCALE_PERCENT = 100
    
    DISTRICT_NAMES = {}
    
    REAPING_MAX_WIDTH = 750
    MAX_TRIBUTES_PER_ROW = 6
    TRIBUTE_IMAGE_SIZE = 90
    TRIBUTE_SPACING = 16
    DISTRICT_SPACING = 16
    EDGE_PADDING = 18
    DISTRICT_LABEL_TO_IMAGES = 0
    TRIBUTE_CARD_INTERNAL_SPACING = 2
    DISTRICT_ROW_SPACING = 16
    PREVIEW_PANEL_SPACING = 16
    TRIBUTE_IMAGE_BORDER_RADIUS = "0px"
    
    TRIBUTE_IMAGE_BORDER_ENABLED = True
    TRIBUTE_IMAGE_BORDER_WIDTH = 1
    TRIBUTE_IMAGE_BORDER_COLOR = "#000000"
    TRIBUTE_IMAGE_BORDER_STYLE = "solid"
    
    TRIBUTE_IMAGE_SHADOW_PRESET = "none"
    TRIBUTE_IMAGE_SHADOW_COLOR = "#000000"
    
    DEAD_TRIBUTE_IMAGE_EFFECT = "grayscale"
    DEAD_TRIBUTE_OPACITY = 0.7
    DEAD_TRIBUTE_BORDER_ENABLED = True
    DEAD_TRIBUTE_BORDER_WIDTH = 2
    DEAD_TRIBUTE_BORDER_COLOR = "#ff0000"
    DEAD_TRIBUTE_BORDER_STYLE = "solid"
    DEAD_TRIBUTE_NAME_COLOR = "#888888"
    
    DEAD_TRIBUTE_SHADOW_PRESET = "none"
    DEAD_TRIBUTE_SHADOW_COLOR = "#000000"
    
    DISTRICT_LABEL_FONT = "Arial"
    DISTRICT_LABEL_SIZE = 16
    DISTRICT_LABEL_BOLD = True
    DISTRICT_LABEL_ITALIC = False
    DISTRICT_LABEL_UNDERLINE = False
    DISTRICT_LABEL_COLOR = "#ffffff"
    DISTRICT_LABEL_SHADOW_PRESET = "none"
    DISTRICT_LABEL_SHADOW_COLOR = "#000000"
    DISTRICT_LABEL_SHADOW_RADIUS_SCALE = 1.0
    DISTRICT_LABEL_SHADOW_CUSTOM = ""
    DISTRICT_LABEL_OUTLINE_STYLE = None
    DISTRICT_LABEL_OUTLINE_COLOR = None
    
    TRIBUTE_NAME_FONT = "Arial"
    TRIBUTE_NAME_SIZE = 11
    TRIBUTE_NAME_BOLD = True
    TRIBUTE_NAME_ITALIC = False
    TRIBUTE_NAME_UNDERLINE = False
    TRIBUTE_NAME_COLOR = "#ffffff"
    TRIBUTE_NAME_SHADOW_PRESET = "none"
    TRIBUTE_NAME_SHADOW_COLOR = "#000000"
    TRIBUTE_NAME_SHADOW_RADIUS_SCALE = 1.0
    TRIBUTE_NAME_SHADOW_CUSTOM = ""
    TRIBUTE_NAME_OUTLINE_STYLE = None
    TRIBUTE_NAME_OUTLINE_COLOR = None
    
    TRIBUTE_STATUS_FONT = "Arial"
    TRIBUTE_STATUS_SIZE = 11
    TRIBUTE_STATUS_BOLD = True
    TRIBUTE_STATUS_ITALIC = False
    TRIBUTE_STATUS_UNDERLINE = False
    TRIBUTE_STATUS_COLOR = "#33FF00"
    TRIBUTE_STATUS_DEAD_COLOR = "#FF0033"
    TRIBUTE_STATUS_SHADOW_PRESET = "none"
    TRIBUTE_STATUS_SHADOW_COLOR = "#000000"
    TRIBUTE_STATUS_SHADOW_RADIUS_SCALE = 1.0
    TRIBUTE_STATUS_SHADOW_CUSTOM = ""
    TRIBUTE_STATUS_OUTLINE_STYLE = None
    TRIBUTE_STATUS_OUTLINE_COLOR = None
    
    REAPING_BG_COLOR = "#5d5050"
    REAPING_BG_IMAGE = ""
    REAPING_BG_SIZE = "cover"
    REAPING_BG_POSITION = "center center"
    REAPING_BG_REPEAT = "no-repeat"
    REAPING_BG_X_OFFSET = "0px"
    REAPING_BG_Y_OFFSET = "0px"
    
    FEED_WIDTH = 679
    FEED_PORTRAIT_MAX_WIDTH = 650
    FEED_TEXT_MAX_WIDTH = 640
    FEED_PORTRAIT_HEIGHT = 90
    FEED_PORTRAIT_SPACING = 16 #check
    FEED_PORTRAITS_TO_TEXT = 15
    FEED_BETWEEN_EVENTS = 15
    FEED_TITLE_TO_EVENTS = 15
    FEED_PORTRAIT_BORDER_RADIUS = "0px"
    
    FEED_PORTRAIT_BORDER_ENABLED = True
    FEED_PORTRAIT_BORDER_WIDTH = 1
    FEED_PORTRAIT_BORDER_COLOR = "#000000"
    FEED_PORTRAIT_BORDER_STYLE = "solid"
    
    FEED_PORTRAIT_SHADOW_PRESET = "none"
    FEED_PORTRAIT_SHADOW_COLOR = "#000000"
    
    FEED_TITLE_FONT = "Arial"
    FEED_TITLE_SIZE = 14
    FEED_TITLE_COLOR = "#ffcf27"
    FEED_TITLE_BOLD = False
    FEED_TITLE_ITALIC = False
    FEED_TITLE_UNDERLINE = False
    FEED_TITLE_BOX_BG_COLOR = "#232323"
    FEED_TITLE_BOX_BG_OPACITY = "Solid"
    FEED_TITLE_BOX_BG_ALPHA = 1.0
    FEED_TITLE_BOX_BORDER_WIDTH = "1"
    FEED_TITLE_BOX_BORDER_COLOR = "#ffffff"
    FEED_TITLE_BOX_PADDING = 5
    FEED_TITLE_SHADOW_PRESET = "none"
    FEED_TITLE_SHADOW_COLOR = "#000000"
    FEED_TITLE_SHADOW_RADIUS_SCALE = 1.0
    FEED_TITLE_SHADOW_CUSTOM = ""
    FEED_TITLE_OUTLINE_STYLE = None
    FEED_TITLE_OUTLINE_COLOR = None
    
    FEED_EVENT_TEXT_FONT = "Arial"
    FEED_EVENT_TEXT_SIZE = 14
    FEED_EVENT_TEXT_BOLD = False
    FEED_EVENT_TEXT_ITALIC = False
    FEED_EVENT_TEXT_UNDERLINE = False
    FEED_TEXT_COLOR = "#ffffff"
    FEED_EVENT_TEXT_SHADOW_PRESET = "none"
    FEED_EVENT_TEXT_SHADOW_COLOR = "#000000"
    FEED_EVENT_TEXT_SHADOW_RADIUS_SCALE = 1.0
    FEED_EVENT_TEXT_SHADOW_CUSTOM = ""
    FEED_EVENT_TEXT_OUTLINE_STYLE = None
    FEED_EVENT_TEXT_OUTLINE_COLOR = None
    
    FEED_BG_COLOR = "#5d5050"
    FEED_BG_X_OFFSET = "0px"
    FEED_BG_Y_OFFSET = "0px"
    DAY_BG_IMAGE = ""
    NIGHT_BG_IMAGE = ""
    BLOODBATH_BG_IMAGE = ""
    WINNER_BG_IMAGE = ""
    STATS_BG_IMAGE = ""
    STATS_BG_COLOR = "#5d5050"
    
    PORTRAIT_GRAYSCALE_ON_GHOST = True
    IMAGE_ASPECT_RATIO_LOCK = True
    
    SEASON_TITLE_ENABLED = True
    PHASE_TITLES_ENABLED = True
    REAPING_TITLE_ENABLED = True
    REAPING_TITLE_TEXT = "Reaping"
    DAY_PHASE_NAME = ""
    NIGHT_PHASE_NAME = ""
    WIN_SCREEN_NAME = ""
    TITLE_BOX_MARGIN_BOTTOM = 15
    
    SEASON_TITLE_TEXT = "The Hunger Games"
    SEASON_TITLE_FONT = "Arial"
    SEASON_TITLE_SIZE = 16
    SEASON_TITLE_COLOR = "#ffcf27"
    SEASON_TITLE_BOLD = False
    SEASON_TITLE_ITALIC = False
    SEASON_TITLE_UNDERLINE = False
    SEASON_TITLE_SHOW = True
    SEASON_TITLE_BOX_BG_COLOR = "#232323"
    SEASON_TITLE_BOX_BG_OPACITY = "Solid"
    SEASON_TITLE_BOX_BG_OPACITY = "Full"
    SEASON_TITLE_SHADOW_PRESET = "none"
    SEASON_TITLE_SHADOW_COLOR = "#000000"
    SEASON_TITLE_SHADOW_RADIUS_SCALE = 1.0
    SEASON_TITLE_SHADOW_CUSTOM = ""
    SEASON_TITLE_OUTLINE_STYLE = None
    SEASON_TITLE_OUTLINE_COLOR = None
    
    PHASE_TITLE_SHADOW_PRESET = "none"
    PHASE_TITLE_SHADOW_COLOR = "#000000"
    PHASE_TITLE_SHADOW_RADIUS_SCALE = 1.0
    PHASE_TITLE_SHADOW_CUSTOM = ""
    PHASE_TITLE_OUTLINE_STYLE = None
    PHASE_TITLE_OUTLINE_COLOR = None
    
    PROCEED_BUTTON_TEXT = "Proceed"
    PROCEED_BUTTON_FONT = "Arial"
    PROCEED_BUTTON_FONT_SIZE = 14
    PROCEED_BUTTON_BOLD = False
    PROCEED_BUTTON_ITALIC = False
    PROCEED_BUTTON_COLOR = "cyan"
    PROCEED_BUTTON_HOVER_COLOR = "#00FFFF"
    PROCEED_BUTTON_MARGIN_TOP = 20
    PROCEED_BUTTON_SHADOW_PRESET = "none"
    PROCEED_BUTTON_SHADOW_COLOR = "#000000"
    PROCEED_BUTTON_OUTLINE_STYLE = None
    PROCEED_BUTTON_OUTLINE_COLOR = None
    
    TEXT_OUTLINE_STYLE = "none"
    TEXT_OUTLINE_COLOR = "#000000"
    TEXT_OUTLINE_WIDTH = 1.0
    TEXT_OUTLINE_SHADOW_SPREAD = 1
    TEXT_OUTLINE_SHADOW_OPACITY = 1.0
    TEXT_OUTLINE_SHADOW_BLUR = 0
    
    SHADOW_COLOR = "#000000"
    SHADOW_COLOR_RGB = "0, 0, 0"
    SHADOW_RADIUS_SCALE = 1.0
    TEXT_SHADOW_BLUR_RADIUS = [2, 5, 10]
    TEXT_SHADOW_STRONG_BLUR_RADIUS = [2, 2, 5, 5, 10, 10]
    
    WINNER_IMAGE_SIZE = 100
    
    PLACEMENTS_BG_IMAGE = ""
    PLACEMENTS_BG_COLOR = "#5d5050"
    PLACEMENTS_TRIBUTE_IMAGE_SIZE = 90
    PLACEMENTS_TRIBUTE_SPACING = 16
    PLACEMENTS_ROW_SPACING = 16
    PLACEMENTS_EDGE_PADDING = 18
    PLACEMENTS_IMAGE_BORDER_RADIUS = "0px"
    PLACEMENTS_MAX_WIDTH = 750

    PLACEMENTS_NAME_FONT = "Arial"
    PLACEMENTS_NAME_SIZE = 11
    PLACEMENTS_NAME_BOLD = True
    PLACEMENTS_NAME_ITALIC = False
    PLACEMENTS_NAME_COLOR = "#ffffff"
    PLACEMENTS_NAME_SHADOW_PRESET = "none"
    PLACEMENTS_NAME_SHADOW_COLOR = "#000000"
    PLACEMENTS_NAME_SHADOW_RADIUS_SCALE = 1.0
    PLACEMENTS_NAME_SHADOW_CUSTOM = ""
    PLACEMENTS_NAME_OUTLINE_STYLE = None
    PLACEMENTS_NAME_OUTLINE_COLOR = None

    PLACEMENTS_RANK_FONT = "Arial"
    PLACEMENTS_RANK_SIZE = 11
    PLACEMENTS_RANK_BOLD = True
    PLACEMENTS_RANK_ITALIC = False
    PLACEMENTS_RANK_COLOR = "#ffffff"
    PLACEMENTS_RANK_SHADOW_PRESET = "none"
    PLACEMENTS_RANK_SHADOW_COLOR = "#000000"
    PLACEMENTS_RANK_SHADOW_RADIUS_SCALE = 1.0
    PLACEMENTS_RANK_SHADOW_CUSTOM = ""
    PLACEMENTS_RANK_OUTLINE_STYLE = None
    PLACEMENTS_RANK_OUTLINE_COLOR = None

    PLACEMENTS_DISTRICT_FONT = "Arial"
    PLACEMENTS_DISTRICT_SIZE = 11
    PLACEMENTS_DISTRICT_BOLD = True
    PLACEMENTS_DISTRICT_ITALIC = False
    PLACEMENTS_DISTRICT_COLOR = "#ffffff"
    PLACEMENTS_DISTRICT_SHADOW_PRESET = "none"
    PLACEMENTS_DISTRICT_SHADOW_COLOR = "#000000"
    PLACEMENTS_DISTRICT_SHADOW_RADIUS_SCALE = 1.0
    PLACEMENTS_DISTRICT_SHADOW_CUSTOM = ""
    PLACEMENTS_DISTRICT_OUTLINE_STYLE = None
    PLACEMENTS_DISTRICT_OUTLINE_COLOR = None

    PLACEMENTS_KILLS_FONT = "Arial"
    PLACEMENTS_KILLS_SIZE = 11
    PLACEMENTS_KILLS_BOLD = True
    PLACEMENTS_KILLS_ITALIC = False
    PLACEMENTS_KILLS_COLOR = "#FFFFFF"
    PLACEMENTS_KILLS_SHADOW_PRESET = "none"
    PLACEMENTS_KILLS_SHADOW_COLOR = "#000000"
    PLACEMENTS_KILLS_SHADOW_RADIUS_SCALE = 1.0
    PLACEMENTS_KILLS_SHADOW_CUSTOM = ""
    PLACEMENTS_KILLS_OUTLINE_STYLE = None
    PLACEMENTS_KILLS_OUTLINE_COLOR = None
    
    PLACEMENTS_IMAGE_BORDER_ENABLED = True
    PLACEMENTS_IMAGE_BORDER_WIDTH = 1
    PLACEMENTS_IMAGE_BORDER_COLOR = "#000000"
    PLACEMENTS_IMAGE_BORDER_STYLE = "solid"

    PLACEMENTS_TITLE_TEXT = "Placements"
    
    AVAILABLE_FONTS = [
        "Arial",
        "Times New Roman",
        "Courier New",
        "Verdana",
        "Georgia",
        "Comic Sans MS",
        "Trebuchet MS",
        "Impact"
    ]

    CUSTOM_FONT_FILES = []
